Document the api endpoints you are required to implement
OpenConext/OpenConext-user-lifecycle pull request #66
Opened 2024-02-23 13:03 UTC by thijskh

It was documented nowhere what endpoints your app needs to support and what they need to do.

2024-05-20 08:05 UTC, parijke approved these changes

2024-05-20 08:05 UTC, parijke commented on config/packages/framework.yaml
> +  esi: false
esi and fragments are both false by default. Do we still want the configure them explicitely?

2024-05-20 08:07 UTC, parijke requested changes

2024-05-20 08:07 UTC, parijke commented on composer.lock
@thijskh whu is the composer.lock file changed? Looks unreleated

2024-05-20 12:16 UTC, thijskh commented on composer.lock
Probably because of the different base branches. Will rebase it

2024-05-21 04:47 UTC, thijskh commented
Replaced by #6

2024-05-21 04:47 UTC, closed without merging